// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv0Ht9AGy9fp2s3cucPAsTg_paMfhxwS8',
    appId: '1:1089620826376:web:b2f2e3b09b92875712f4bd',
    messagingSenderId: '1089620826376',
    projectId: 'fir-labb-1e4c2',
    authDomain: 'fir-labb-1e4c2.firebaseapp.com',
    storageBucket: 'fir-labb-1e4c2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB9E1XajkgbrFm6IQ9EuBNwfhk0h6x3Vs',
    appId: '1:1089620826376:android:7f5da02391c5a60e12f4bd',
    messagingSenderId: '1089620826376',
    projectId: 'fir-labb-1e4c2',
    storageBucket: 'fir-labb-1e4c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy0P2-aaJT_W-cSaKIbm52RqExXixek2E',
    appId: '1:1089620826376:ios:1dcba0bcbb9f94ea12f4bd',
    messagingSenderId: '1089620826376',
    projectId: 'fir-labb-1e4c2',
    storageBucket: 'fir-labb-1e4c2.appspot.com',
    iosBundleId: 'com.example.firebaseLabb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy0P2-aaJT_W-cSaKIbm52RqExXixek2E',
    appId: '1:1089620826376:ios:2437afc42a2648d712f4bd',
    messagingSenderId: '1089620826376',
    projectId: 'fir-labb-1e4c2',
    storageBucket: 'fir-labb-1e4c2.appspot.com',
    iosBundleId: 'com.example.firebaseLabb.RunnerTests',
  );
}
